### ISSUE TITLE
Doesn't work with new importmaps-rails

### ISSUE THREAD

**Issue by woodardj** [stimulus-components/stimulus-chartjs#3]
Attempting to `pin` this dependency via importmaps results in the following error:

```
$ ./bin/importmap pin stimulus-chartjs
Couldn't find any packages in ["stimulus-chartjs"] on jspm
```

This might be an upstream error (i.e. an issue with chart.js), but I thought it was worth calling out on this repo.

**Comment by guillaumebriday** [comment]
It should now works 👍
